spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beats
    username: coder
    password: coder123
  jpa:
    hibernate:
      ddl-auto: update # for schema update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day 86400000
      refresh-token:
        expiration: 604800000 # 7 days
server:
  reactive:
    session:
      cookie:
        same-site: lax
logging:
  level:
    web: info
